### ISSUE TITLE
Consider removing iterator and yielder support

### ISSUE THREAD

**Issue by lpil** [fschwalbe/glearray#2]
Hello!

I would like to propose removing these two functions.

Removing the iterator one is required for this library to work with current stdlib.

The yielder function is an example of misuse of that library. It is only to be used for generating sequences that cannot fit into memory, and the use in this library always fits into memory, so it exists purely as overhead without benefit. It also has a chance to mislead folks into writing suboptimal code, giving the impression that it is a good use of yielder. It would be nice to remove the extra dependency too!

Thank you

**Comment by lunagl** [comment]
Hey, thanks for the feedback!
I'm gonna remove the `iterate` function of course, but I am wondering why `yielder` is only appropriate for sequences that cannot fit into memory? Many languages have some sort of iterator/stream/sequences concept, which usually allows all kinds of data sources (in-memory collections, potentially infinite streams, etc), and gives users a unified API to work with those (`map`, `reduce`, etc). Is gleam/yielder not meant for this purpose? The other option would be converting the array to a list, doing operations on the list and converting it back, but especially for large arrays that seems like a lot of potential overhead.

**Comment by lpil** [comment]
It's not suitable because it adds a large overhead to the iteration. Using non yielder iteration methods will always be impactfully faster.

It was removed from stdlib as people kept making the mistake you're making there, resulting in them writing code that was both more complex and slower. Ideally we would have deleted that module altogether, but that would be too irritating for projects that already use it, so we now have the yielder package and do not publicise it to discourage its use.

If folks really do want to use this library with yielder it's trivial to write the function they need, and they are already going to be writing complex niche code to need such a niche data structure, so it is no bother for them there.

**Comment by lunagl** [comment]
That's good to know, thanks for the explanation. And you're right, the yield function is quite trivial to implement, so I will delete it.

**Comment by lunagl** [comment]
Both functions have been removed and v2.0.0 is published! Sorry for the delay, and thanks again for your advice <3
